Fix callback_message missing `conn` argument
```
01:59:11 ERROR    errbot.errBot             Crash in a callback_message
handler
Traceback (most recent call last):
  File "/Users/lekov/Workspace/elsys/errbot/errbot/errBot.py", line
523, in callback_message
    plugin.callback_message(mess)
TypeError: callback_message() missing 1 required positional argument:
'message'
```
https://github.com/errbotio/errbot/blob/master/errbot/botplugin.py#L258